/** 技能中文描述映射（key = SKILL.md 中的 name 字段，即文件夹名） */
export const SKILL_CN: Record<string, string> = {
  '1password': '1Password密钥管理与注入',
  'apple-notes': '苹果备忘录创建编辑与搜索',
  'apple-reminders': '苹果提醒事项管理与查看',
  'bear-notes': 'Bear笔记创建与管理(macOS)',
  'blogwatcher': '博客RSS源监控与更新',
  'blucli': 'Bluesound音箱播放控制',
  'bluebubbles': 'iMessage消息发送与管理',
  'camsnap': 'RTSP摄像头截图与录制',
  'canvas': '在连接设备显示HTML内容',
  'clawhub': 'ClawHub技能搜索安装发布',
  'coding-agent': '运行Codex/Claude Code编程',
  'discord': 'Discord消息反应与管理',
  'eightctl': 'Eight Sleep床垫温度控制',
  'food-order': 'Foodora订单重新下单与追踪',
  'gemini': 'Google Gemini一次性提问',
  'gifgrep': 'GIF搜索下载与提取',
  'github': 'GitHub问题PR与CI管理',
  'gog': 'Google邮件日历文档',
  'goplaces': 'Google地点搜索与查询',
  'healthcheck': '主机安全审计与加固',
  'himalaya': 'IMAP/SMTP邮件客户端',
  'imsg': 'iMessage/SMS消息收发(macOS)',
  'mcporter': 'MCP服务器工具直接调用',
  'model-usage': '模型成本使用统计(macOS)',
  'nano-banana-pro': 'Gemini图像生成与编辑',
  'nano-pdf': 'PDF自然语言编辑',
  'notion': 'Notion页面数据库管理',
  'obsidian': 'Obsidian笔记库自动化',
  'openai-image-gen': 'OpenAI图像批量生成',
  'openai-whisper-api': 'OpenAI语音转文字API',
  'openai-whisper': '本地离线语音转文字',
  'openhue': 'Philips Hue灯光场景控制',
  'oracle': '代码库一次性提问工具',
  'ordercli': 'Foodora订单查询与追踪',
  'peekaboo': 'macOS UI自动化与截图',
  'sag': 'ElevenLabs文字转语音',
  'session-logs': '搜索分析历史对话记录',
  'sherpa-onnx-tts': '本地离线文字转语音',
  'skill-creator': '创建打包自定义技能',
  'slack': 'Slack消息反应与管理',
  'songsee': '音频频谱图与特征可视化',
  'sonoscli': 'Sonos音箱播放控制',
  'spotify-player': 'Spotify播放与搜索',
  'summarize': 'URL视频文件内容总结',
  'things-mac': 'Things 3任务管理(macOS)',
  'tmux': '远程控制tmux交互会话',
  'trello': 'Trello看板卡片管理',
  'video-frames': '视频帧提取与截图',
  'voice-call': '语音通话发起与管理',
  'wacli': 'WhatsApp消息发送与搜索',
  'weather': '天气预报查询(无需密钥)',
}
