/** 技能中文描述映射（key = SKILL.md 中的 name 字段） */
export const SKILL_CN: Record<string, string> = {
  '1Password': '1Password密钥管理与注入',
  'Apple笔记': '苹果备忘录创建编辑与搜索',
  'Apple提醒事项': '苹果提醒事项管理与查看',
  'Bear笔记': 'Bear笔记创建与管理(macOS)',
  '博客监控器': '博客RSS源监控与更新',
  'BluOS命令行工具': 'Bluesound音箱播放控制',
  'BlueBubbles': 'iMessage消息发送与管理',
  '摄像头快照': 'RTSP摄像头截图与录制',
  'ClawdHub': 'ClawHub技能搜索安装发布',
  '编程代理': '运行Codex/Claude Code编程',
  'Discord': 'Discord消息反应与管理',
  '八度睡眠控制器': 'Eight Sleep床垫温度控制',
  '食物订购': 'Foodora订单重新下单与追踪',
  'Gemini': 'Google Gemini一次性提问',
  'GIF搜索器': 'GIF搜索下载与提取',
  'GitHub': 'GitHub问题PR与CI管理',
  '谷歌工作区': 'Google邮件日历文档',
  '地点搜索': 'Google地点搜索与查询',
  '喜马拉雅邮件': 'IMAP/SMTP邮件客户端',
  'iMessage短信': 'iMessage/SMS消息收发(macOS)',
  'MC Porter': 'MCP服务器工具直接调用',
  '模型使用情况': '模型成本使用统计(macOS)',
  '纳米香蕉专业版': 'Gemini图像生成与编辑',
  '纳米PDF': 'PDF自然语言编辑',
  'Notion': 'Notion页面数据库管理',
  'Obsidian': 'Obsidian笔记库自动化',
  'OpenAI图像生成': 'OpenAI图像批量生成',
  'OpenAI Whisper API': 'OpenAI语音转文字API',
  'OpenAI Whisper': '本地离线语音转文字',
  'OpenHue': 'Philips Hue灯光场景控制',
  'Oracle': '代码库一次性提问工具',
  '订单CLI': 'Foodora订单查询与追踪',
  'Peekaboo': 'macOS UI自动化与截图',
  'SAG': 'ElevenLabs文字转语音',
  '会话日志': '搜索分析历史对话记录',
  '本地语音合成': '本地离线文字转语音',
  '技能创建器': '创建打包自定义技能',
  'Slack': 'Slack消息反应与管理',
  '音频可视化': '音频频谱图与特征可视化',
  'Sonos控制器': 'Sonos音箱播放控制',
  'Spotify播放器': 'Spotify播放与搜索',
  '内容摘要': 'URL视频文件内容总结',
  'Things管理': 'Things 3任务管理(macOS)',
  'Tmux会话控制': '远程控制tmux交互会话',
  'Trello管理': 'Trello看板卡片管理',
  '视频帧提取': '视频帧提取与截图',
  '语音通话': '语音通话发起与管理',
  'WhatsApp命令行工具': 'WhatsApp消息发送与搜索',
  '天气查询': '全球天气查询与预报(无需密钥)',
  '新闻资讯': '中文新闻与AI技术资讯(无需密钥)',
  '百度搜索': '百度AI搜索、百科、智能问答',
  '高德地图': '路线规划与POI地点搜索',
  '邮件管理': 'QQ/163邮箱收发邮件',
  '图片分析': '智谱GLM-4V图片分析与OCR',
  'AI 图片生成': '智谱CogView文字生成图片',
  '网页设计部署': 'HTML网页生成与Cloudflare部署',
  '本地地点': '本地地点搜索',
  'windows-control': 'Windows桌面控制与浏览器自动化',
}
